export const MAIN = '/'
export const LOGIN = '/login'
export const REGISTRATION = '/registration'
export const CREATE_TEST = '/test/create'
export const TEST_SET = '/user/tests'
export const GET_TEST = '/user/test'
export const TEST_FOR_CLIENT = '/open/test' 
export const TESTS = '/tests'
