export const MAIN = '/'
export const LOGIN = '/login'
export const REGISTRATION = '/registration'
export const TESTS = '/tests'
export const MAIN_TEST = '/test/main'
export const CREATE_TEST = '/test/create'
export const TEST_SET = '/test/set'
export const TEST_FOR_CLIENT = '/test/client' 
